mutation bootstrap {
  addProducerTypeEnums(
    input: [
      { id: "OilWell" }
      { id: "OilRefinery" }
      { id: "CoalMine" }
      { id: "PowerPlant" }
      { id: "Forest" }
      { id: "LumberMill" }
      { id: "TextileMill" }
      { id: "Factory" }
      { id: "Farm" }
      { id: "Warehouse" }
      { id: "Cotton" }
    ]
  )

  addResources(
    input: [
      {
        id: "PowerPlant:0:Energy"
        sim: "Default"
        type: "Energy"
        capacity: 1000
        quantity: 1000
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "PowerPlant:1:Energy"
        sim: "Default"
        type: "Energy"
        capacity: 1000
        quantity: 1000
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "OilWell:0:Product:Crude"
        sim: "Default"
        type: "Crude"
        capacity: 1000
        quantity: 1000
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "OilRefinery:0:Material:Crude"
        sim: "Default"
        type: "Crude"
        capacity: 1000
        quantity: 1000
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "OilRefinery:0:Product:Petrochemicals"
        sim: "Default"
        type: "Petrochemicals"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "CoalMine:0:Product:Coal"
        sim: "Default"
        type: "Coal"
        capacity: 1000
        quantity: 1000
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "PowerPlant:0:Material:Coal"
        sim: "Default"
        type: "Coal"
        capacity: 1000
        quantity: 100
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "PowerPlant:1:Material:Coal"
        sim: "Default"
        type: "Coal"
        capacity: 1000
        quantity: 100
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Farm:0:Product:Food"
        sim: "Default"
        type: "Food"
        capacity: 100
        quantity: 50
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Farm:1:Product:Food"
        sim: "Default"
        type: "Food"
        capacity: 100
        quantity: 50
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Forest:0:Product:Trees"
        sim: "Default"
        type: "Trees"
        capacity: 1000
        quantity: 1000
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Forest:1:Product:Trees"
        sim: "Default"
        type: "Trees"
        capacity: 1000
        quantity: 1000
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:0:Product:Petrochemicals"
        sim: "Default"
        type: "Petrochemicals"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:0:Product:Food"
        sim: "Default"
        type: "Food"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:0:Product:Goods"
        sim: "Default"
        type: "Goods"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:0:Product:Lumber"
        sim: "Default"
        type: "Lumber"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:0:Product:Textiles"
        sim: "Default"
        type: "Textiles"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:1:Product:Petrochemicals"
        sim: "Default"
        type: "Petrochemicals"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:1:Product:Food"
        sim: "Default"
        type: "Food"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:1:Product:Goods"
        sim: "Default"
        type: "Goods"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:1:Product:Lumber"
        sim: "Default"
        type: "Lumber"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Warehouse:1:Product:Textiles"
        sim: "Default"
        type: "Textiles"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Textile:0:Material:Cotton"
        sim: "Default"
        type: "Cotton"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Textile:0:Product:Textile"
        sim: "Default"
        type: "Textile"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Cotton:0:Product:Cotton"
        sim: "Default"
        type: "Cotton"
        capacity: 10000
        quantity: 100
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Factory:0:Material:Petrochemicals"
        sim: "Default"
        type: "Petrochemicals"
        capacity: 1000
        quantity: 10
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Factory:0:Material:Textiles"
        sim: "Default"
        type: "Textiles"
        capacity: 1000
        quantity: 10
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Factory:0:Material:Lumber"
        sim: "Default"
        type: "Lumber"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "Factory:0:Product:Goods"
        sim: "Default"
        type: "Goods"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "LumberMill:0:Material:Trees"
        sim: "Default"
        type: "Trees"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
      {
        id: "LumberMill:0:Product:Lumber"
        sim: "Default"
        type: "Lumber"
        capacity: 1000
        quantity: 0
        basePricePerUnit: 1
        adjustedPricePerUnit: 1
        scarcitySurchargeFactor: 1
        replenishRate: 0
        consumptionRate: 1
      }
    ]
  )

  addProducers(
    input: [
      {
        id: "OilWell:0"
        sim: "Default"
        type: "OilWell"
        material: ["PowerPlant:0:Energy"]
        products: ["OilWell:0:Product:Crude"]
        stoppageSurchargeFactor: 0.1
        x: 0
        y: 0
        steps: 0
        yRot: 0
      }
      {
        id: "OilRefinery:0"
        sim: "Default"
        type: "OilRefinery"
        material: ["OilRefinery:0:Material:Crude", "PowerPlant:0:Energy"]
        products: ["OilRefinery:0:Product:Petrochemicals"]
        stoppageSurchargeFactor: 0.1
        x: 2
        y: 0
        steps: 0
        yRot: 0
      }
      {
        id: "CoalMine:0"
        sim: "Default"
        type: "CoalMine"
        material: ["PowerPlant:0:Energy"]
        products: ["CoalMine:0:Product:Coal"]
        stoppageSurchargeFactor: 0.1
        x: 4
        y: 0
        steps: 0
        yRot: 0
      }
      {
        id: "PowerPlant:0"
        sim: "Default"
        type: "PowerPlant"
        material: ["PowerPlant:0:Material:Coal"]
        products: ["PowerPlant:0:Energy"]
        stoppageSurchargeFactor: 0.1
        x: 6
        y: 1
        steps: 0
        yRot: 180
      }
      {
        id: "PowerPlant:1"
        sim: "Default"
        type: "PowerPlant"
        material: ["PowerPlant:1:Material:Coal"]
        products: ["PowerPlant:1:Energy"]
        stoppageSurchargeFactor: 0.1
        x: 7
        y: 9
        steps: 0
        yRot: 0
      }
      {
        id: "Farm:0"
        sim: "Default"
        type: "Farm"
        material: ["PowerPlant:1:Energy"]
        products: ["Farm:0:Product:Food"]
        stoppageSurchargeFactor: 0.1
        x: 11
        y: 4
        steps: 0
        yRot: 90
      }
      {
        id: "Farm:1"
        sim: "Default"
        type: "Farm"
        material: ["PowerPlant:1:Energy"]
        products: ["Farm:1:Product:Food"]
        stoppageSurchargeFactor: 0.1
        x: 11
        y: 5
        steps: 0
        yRot: 90
      }
      {
        id: "Forest:0"
        sim: "Default"
        type: "Forest"
        material: []
        products: ["Forest:0:Product:Trees"]
        stoppageSurchargeFactor: 0.1
        x: 5
        y: 10
        steps: 0
        yRot: 90
      }
      {
        id: "Forest:1"
        sim: "Default"
        type: "Forest"
        material: []
        products: ["Forest:1:Product:Trees"]
        stoppageSurchargeFactor: 0.1
        x: 6
        y: 11
        steps: 0
        yRot: 0
      }
      {
        id: "Warehouse:0"
        sim: "Default"
        type: "Warehouse"
        material: [
          "Warehouse:0:Product:Petrochemicals"
          "Warehouse:0:Product:Food"
          "Warehouse:0:Product:Goods"
          "Warehouse:0:Product:Lumber"
          "Warehouse:0:Product:Textiles"
        ]
        products: [
          "Warehouse:0:Product:Petrochemicals"
          "Warehouse:0:Product:Food"
          "Warehouse:0:Product:Goods"
          "Warehouse:0:Product:Lumber"
          "Warehouse:0:Product:Textiles"
        ]
        stoppageSurchargeFactor: 0.1
        x: 5
        y: 3
        steps: 0
        yRot: 0
      }
      {
        id: "Warehouse:1"
        sim: "Default"
        type: "Warehouse"
        material: [
          "Warehouse:1:Product:Petrochemicals"
          "Warehouse:1:Product:Food"
          "Warehouse:1:Product:Goods"
          "Warehouse:1:Product:Lumber"
          "Warehouse:0:Product:Textiles"
        ]
        products: [
          "Warehouse:1:Product:Petrochemicals"
          "Warehouse:1:Product:Food"
          "Warehouse:1:Product:Goods"
          "Warehouse:1:Product:Lumber"
          "Warehouse:0:Product:Textiles"
        ]
        stoppageSurchargeFactor: 0.1
        x: 8
        y: 4
        steps: 0
        yRot: -90
      }
      {
        id: "TextileMill:0"
        sim: "Default"
        type: "TextileMill"
        material: ["Textile:0:Material:Cotton", "PowerPlant:0:Energy"]
        products: ["Textile:0:Product:Textile"]
        stoppageSurchargeFactor: 0.1
        x: 0
        y: 4
        steps: 0
        yRot: 0
      }
      {
        id: "Cotton:0"
        sim: "Default"
        type: "Cotton"
        material: []
        products: ["Cotton:0:Product:Cotton"]
        stoppageSurchargeFactor: 0.1
        x: 0
        y: 6
        steps: 0
        yRot: 0
      }
      {
        id: "Factory:0"
        sim: "Default"
        type: "Factory"
        material: [
          "Factory:0:Material:Petrochemicals"
          "Factory:0:Material:Textiles"
          "Factory:0:Material:Lumber"
          "PowerPlant:1:Energy"
        ]
        products: ["Factory:0:Product:Goods"]
        stoppageSurchargeFactor: 0.1
        x: 11
        y: 7
        steps: 0
        yRot: 0
      }
      {
        id: "LumberMill:0"
        sim: "Default"
        type: "LumberMill"
        material: ["LumberMill:0:Material:Trees", "PowerPlant:1:Energy"]
        products: ["LumberMill:0:Product:Lumber"]
        stoppageSurchargeFactor: 0.1
        x: 9
        y: 11
        steps: 0
        yRot: 0
      }
    ]
  )
}
