mutation bootstrap {
  addResourceTypeEnums(
    input: [
      { id: "Crude" }
      { id: "Petrochemicals" }
      { id: "Coal" }
      { id: "Energy" }
      { id: "Trees" }
      { id: "Lumber" }
      { id: "Cotton" }
      { id: "Textiles" }
      { id: "Goods" }
      { id: "Food" }
    ]
  )
}
